# Generated by Django 4.2.3 on 2023-07-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='product_price',
            new_name='pizza_price',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='product_brand',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='product_pic',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='product_size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_category',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Burger', 'Burger'), ('Paratha', 'Paratha'), ('Pizza_mania', 'Pizza_mania')], default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_pic',
            field=models.ImageField(default='', upload_to='pizza_pic'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_size',
            field=models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_types',
            field=models.CharField(choices=[('Farmhouse_pizza', 'Farmhouse_pizza'), ('Peppy_paneer_pizza', 'Peppy_paneer_pizza'), ('Mexican_green_wave_pizza', 'Mexican_green_wave_pizza'), ('Deluxe_veggie_pizza', 'Deluxe_veggie_pizza'), ('Classic_burger_pizza', 'Classic_burger_pizza'), ('Premium burger_pizza', 'Premium_burger_pizza'), ('Corn_n_cheese_paratha pizza', 'Corn_n_cheese_paratha_pizza'), ('Paneer_paratha_pizza', 'Paneer_paratha_pizza'), ('Cheesy_pizza', 'Cheesy_pizza'), ('Paneer_&_onion_pizza', 'Paneer_&_onion_pizza'), ('Golden_corn_pizza', 'Golden_corn_pizza'), ('Cheese_n_tomato_pizza', 'Cheese_n_tomato_pizza')], default=0, max_length=100),
        ),
    ]
